spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jun?serverTimezone=Asia/Shanghai
    username: root
    password: root

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 输出 SQL 到控制台
logging:
  level:
    com.baomidou.mybatis plus: DEBUG
    org.mybatis: DEBUG


